security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            provider: app_user_provider
            lazy: true
            form_login:
                login_path: app_login  # Modifié ici
                check_path: app_login  # Modifié ici
                enable_csrf: true
                csrf_token_id: authenticate
            logout:
                path: app_logout  # Utilise le nom de route défini
                target: /
            entry_point: form_login  # Spécifiez le point d'entrée ici

    access_control:
        - { path: ^/employee, roles: ROLE_EMPLOYEE }
