security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            provider: app_user_provider
            lazy: true
            form_login:
                login_path: app_login 
                check_path: app_login  
                enable_csrf: true
                csrf_token_id: authenticate
                username_parameter: email
                password_parameter: password
            logout:
                path: app_logout 
                target: /
            entry_point: form_login 

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/employee, roles: ROLE_EMPLOYEE }
